[tool.poetry]
name = "ekklesia-notify"
version = "2020.07.0"
description = "Notification service for Ekklesia apps"
authors = ["Tobias dpausp <dpausp@posteo.de>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.60.1"
uvicorn = "^0.11.6"
matrix-nio = {extras = ["all"], version = "^0.14.1"}

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
